### ISSUE TITLE
[TODO] restructure static site docs

### ISSUE THREAD

**Issue by ITProKyle** [onicagroup/runway#291]
Mimic the other module docs

- [x] create directory named after the module type
- [x] create three files in the new directory: configuration.rst, directory_structure.rst, advanced_features.rst
- [x] (optional) create an examples.rst file in the directory
- [x] move the contents of the `module_configurations` file for the module type to these new files and delete the old file. some minor rewrite may be required.
- [x] add a section to `index.rst` with a toctree for the new addition.
