### ISSUE TITLE
[TODO] restructure kubernetes docs

### ISSUE THREAD

**Issue by ITProKyle** [onicagroup/runway#292]
Mimic the other module docs

- [ ] create directory named after the module type
- [ ] create three files in the new directory: configuration.rst, directory_structure.rst, advanced_features.rst
- [ ] (optional) create an examples.rst file in the directory
- [ ] move the contents of the `module_configurations` file for the module type to these new files and delete the old file. some minor rewrite may be required.
- [ ] add a section to `index.rst` with a toctree for the new addition.
