### ISSUE TITLE
[REQUEST] change `init` command to run pre-deploy actions of IaC tools

### ISSUE THREAD

**Issue by ITProKyle** [onicagroup/runway#427]
# Summary

In #426, the function of `runway init` will become deprecated and replaced with an improved system.

This will free it up to expose the `init` (pre-deploy) commands of underlying IaC tools to prepare an AWS account for deployment outside of `deploy`.

Release of this change will need to wait for a major release.

# Proposal

`runway init` will function similar to `runway deploy` in that it will iterate over each deployment/module/region in order and deploy environments. For each non-skipped module, it will run the appropriate pre-deployment command for the module type (e.g. `terraform init`, `cdk bootstrap`).

In doing this, we should also create a similar action for CFNgin that will deploy a CFNgin bucket if needed. We will need to look for a way to determine if a stack will be deploying the bucket for those that prefer to deploy their own.

# Tasks

_**[NOTE]: Tasks may be split across multiple releases.**_

- [x] add `init()` method to all classes in `runway.modules` - log that it's not supported for the time being (#678)
- [x] add `init` command handling to deployment/module processing (#659)
- [x] add functionality to `init` command (#677)
- [x] add functionality to `CloudDevelopmentKit.init()` (#771)
- [x] add `init` action for CFNgin and add functionality to `CloudFormation.init()` (#722)
- [x] investigate if k8s has/needs an init step and add the functionality to `K8s.init()` if needed
- [x] investigate if serverless has/needs an init step and add the functionality to `Serverless.init()` if needed
- [x] investigate if static site needs an init step and add the functionality to `StaticSite.init()` if needed
- [x] add functionality to `Terraform.init()` (#772)

**Comment by ITProKyle** [comment]
For Serverless, the only potential option I can see is to run `serverless package`. However, this seems more like a _build_ step than initialization.

- It's not _required_ to run a `serverless deploy` (it is run in the background by the command though).
- It only creates artifacts which can then only be used with the `serverless deploy` command.
- The functionality of any other Serverless command is not depended upon it being run.

If it were possible to create the Serverless deployment bucket in a reasonable manor (e.g. via a command with some flags) it would be a perfect fit. I don't see a way of accomplishing this without running `serverless package`, trusting that it will output a CloudFormation template to create the bucket (not always the case), then forwarding the template to CFNgin to deploy.

If there is enough desire for something like that, we can look into doing it in the future but for now I am going to leave the `.init()` method for Serverless blank.

**Comment by ITProKyle** [comment]
For Kubernetes, I don't see anything that would match the intended functionality of `.init()`. I am open to suggestions if anyone thinks otherwise.

**Comment by ITProKyle** [comment]
For static site, the only thing I can think of that would be an init set would be to create a CFNgin bucket like CFNgin modules do. However, static site does not use a CFNgin bucket (`cfngin_bucket: ""` is used) so it does not make sense to run through the process.
