### ISSUE TITLE
[TODO] support planning for destroy

### ISSUE THREAD

**Issue by ITProKyle** [onicagroup/runway#703]
# Summary

Creates a plan whose goal is to destroy all remote objects that currently exist. This can be useful for situations like transient development environments, where the managed objects cease to be useful once the development task is complete.

The idea for this implementation is based around [`terraform apply -destroy`](https://www.terraform.io/docs/cli/commands/plan.html#planning-modes).

# Tasks

- [ ] add `--destroy` option to `runway plan`
- [ ] add handling for passing options like this to deployment/module processing (e.g. `<instance>.plan(destroy=True)`
  - may need to be part of context
  - may need to be translated to a different _command_ on the backend that calls a specific class method (e.g. `.plan_destroy()`)
- [ ] modify module handler classes as needed once the design is finalized
  - for the first pass, just log that its not supported
- [ ] add `--destroy` logic to CDK
- [ ] add `--destroy` logic to Cloudformation
- [ ] add `--destroy` logic to Kubernetes
- [ ] add `--destroy` logic to Serverless
- [ ] add `--destroy` logic to static site
- [ ] add `--destroy` logic to Terraform
